### ISSUE TITLE
Environment dependencies help!!!

### ISSUE THREAD

**Issue by InUszy** [poorting/nfdump2clickhouse#1]
Glad to meet you here author! Something stuck my way to use this tool.
I'll appreciate that you can provide the environment dependencies with detail information(the version of apache arrow, gcc and so on), when execute 'pip install -r requirements.txt'.
Now, it print
```
/usr/include/arrow/visit_type_inline.h:54:5: error: no matching function for call to 'arrow::py::{anonymous}::ObjectWriterVisitor::Visit(const arrow::LargeListType&)'
         54 |     ARROW_GENERATE_FOR_ALL_TYPES(TYPE_VISIT_INLINE);
/tmp/pip-install-vp0fn98s/pyarrow_f6be98e2356e4bb2aa13f3634566ad3a/pyarrow/src/arrow/python/arrow_to_pandas.cc:1223:32: note:   template argument deduction/substitution failed:
      /tmp/pip-install-vp0fn98s/pyarrow_f6be98e2356e4bb2aa13f3634566ad3a/pyarrow/src/arrow/python/arrow_to_pandas.cc:1234:37: note: candidate: 'template<class Type> arrow::enable_if_timestamp<Type, arrow::Status> arrow::py::{anonymous}::ObjectWriterVisitor::Visit(const Type&)'
       1234 |   enable_if_timestamp<Type, Status> Visit(const Type& type) {
```
on it's compiling process.

Thank you!

**Comment by poorting** [comment]
The requirements aren't anything special, so I'm suprised you get this message. What OS/version and python version are you using? I haven't had any issues so fat with various linux systems and MacOS and Python 3.9/3.11
You could try to do 'pip install wheel' first to see if that helps.

**Comment by InUszy** [comment]
> The requirements aren't anything special, so I'm suprised you get this message. What OS/version and python version are you using? I haven't had any issues so fat with various linux systems and MacOS and Python 3.9/3.11 You could try to do 'pip install wheel' first to see if that helps.

Thanks for your quick reply!

OS image: alpine:latest
python: 3.11.9

It seems nothing changed after I did 'pip install wheel' :

```
(venv) /tmp/nfdump2clickhouse-main # pip install -i https://pypi.tuna.tsinghua.edu.cn/simple wheel
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting wheel
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/7d/cd/d7460c9a869b16c3dd4e1e403cce337df165368c71d6af229a74699622ce/wheel-0.43.0-py3-none-any.whl (65 kB)
Installing collected packages: wheel
Successfully installed wheel-0.43.0
```
Error logs here:
```
Building wheels for collected packages: pyarrow
  Building wheel for pyarrow (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pyarrow (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [1053 lines of output]
      <string>:34: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      WARNING setuptools_scm.pyproject_reading toml section missing 'pyproject.toml does not contain a tool.setuptools_scm section'
      Traceback (most recent call last):
        File "/tmp/pip-build-env-aazy5wqy/overlay/lib/python3.11/site-packages/setuptools_scm/_integration/pyproject_reading.py", line 36, in read_pyproject
          section = defn.get("tool", {})[tool_name]
                    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
      KeyError: 'setuptools_scm'
```

**Comment by poorting** [comment]
I haven't tested this with (nor did I intend to use) a docker image. 
Please note also that the issue here is with installing a python package (pyarrow), not with nfdump2clickhouse itself, and alpine docker images are not the most suitable image for python work: https://pythonspeed.com/articles/base-image-python-docker-images/

May I suggest using a more full fledged image e.g. based on debian. Once you get things working you could try to use smaller images if really needed, but I really can't help you with that as it is impossible to support all variations out there.

**Comment by InUszy** [comment]
> I haven't tested this with (nor did I intend to use) a docker image. Please note also that the issue here is with installing a python package (pyarrow), not with nfdump2clickhouse itself, and alpine docker images are not the most suitable image for python work: https://pythonspeed.com/articles/base-image-python-docker-images/
> 
> May I suggest using a more full fledged image e.g. based on debian. Once you get things working you could try to use smaller images if really needed, but I really can't help you with that as it is impossible to support all variations out there.

Got it. Thank you. Has helped me a lot then. I'll try it with other version of OS.
